services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    restart: always
    init: true
  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    init: true
  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: nginx:inception
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    restart: always
    init: true

networks:
  inception:
    driver: bridge

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb_vol
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress_vol

# DATA_PATHは /home/$(whoami)/data という想定
