services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    restart: always
    init: true
  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    init: true
  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: nginx:inception
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    restart: always
    init: true

networks:
  inception:
    driver: bridge

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb_vol
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress_vol

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

# DATA_PATHは /home/$(whoami)/data という想定
