local_enable=YES
anonymous_enable=NO
listen=YES
listen_port=21
port_enable=NO
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009
pasv_address=127.0.0.1
chroot_local_user=YES
allow_writeable_chroot=YES
ssl_enable=YES
rsa_cert_file=/etc/vsftpd/ssl/ftp.crt
rsa_private_key_file=/etc/vsftpd/ssl/ftp.key
ssl_tlsv12=YES
ssl_tlsv13=YES
write_enable=YES
